### ISSUE TITLE
Travis CI integration w/ Poetry

### ISSUE THREAD

**Issue by sdhutchins** [datasnakes/rut#18]
Should be something similar to the below configuration...

```yaml
language: python
python:
- 3.6
before_install:
- pip install poetry
install:
- poetry install
script:
- poetry run flake8 my_package test
- poetry run coverage run --source=my_package -m unittest discover -b
```
